In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [2]:
df=pd.read_csv(r"D:\JAIMIN\Data Science\Machine Learning\admission_data.csv")

In [3]:
df.isnull().sum()

GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [4]:
df.duplicated().sum()

0

In [5]:
df.describe()

GRE Score  TOEFL Score  University Rating         SOP       LOR   \
count  500.000000   500.000000         500.000000  500.000000  500.00000   
mean   316.472000   107.192000           3.114000    3.374000    3.48400   
std     11.295148     6.081868           1.143512    0.991004    0.92545   
min    290.000000    92.000000           1.000000    1.000000    1.00000   
25%    308.000000   103.000000           2.000000    2.500000    3.00000   
50%    317.000000   107.000000           3.000000    3.500000    3.50000   
75%    325.000000   112.000000           4.000000    4.000000    4.00000   
max    340.000000   120.000000           5.000000    5.000000    5.00000   

             CGPA    Research  Chance of Admit   
count  500.000000  500.000000         500.00000  
mean     8.576440    0.560000           0.72174  
std      0.604813    0.496884           0.14114  
min      6.800000    0.000000           0.34000  
25%      8.127500    0.000000           0.63000  
50%      8.560000    1.000000           0.72000  
75%      9.040000    1.000000           0.82000  
max      9.920000    1.000000           0.97000

In [6]:
df

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0          337          118                  4  4.5   4.5  9.65         1   
1          324          107                  4  4.0   4.5  8.87         1   
2          316          104                  3  3.0   3.5  8.00         1   
3          322          110                  3  3.5   2.5  8.67         1   
4          314          103                  2  2.0   3.0  8.21         0   
..         ...          ...                ...  ...   ...   ...       ...   
495        332          108                  5  4.5   4.0  9.02         1   
496        337          117                  5  5.0   5.0  9.87         1   
497        330          120                  5  4.5   5.0  9.56         1   
498        312          103                  4  4.0   5.0  8.43         0   
499        327          113                  4  4.5   4.5  9.04         0   

     Chance of Admit   
0                0.92  
1                0.76  
2                0.72  
3                0.80  
4                0.65  
..                ...  
495              0.87  
496              0.96  
497              0.93  
498              0.73  
499              0.84  

[500 rows x 8 columns]

In [7]:
df.columns

Index(['GRE Score', 'TOEFL Score', 'University Rating', 'SOP', 'LOR ', 'CGPA',
       'Research', 'Chance of Admit '],
      dtype='object')

In [8]:
y = df[['Chance of Admit ']]
y.head()

Chance of Admit 
0              0.92
1              0.76
2              0.72
3              0.80
4              0.65

In [9]:
x =df.drop(columns =["Chance of Admit "])
x

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0          337          118                  4  4.5   4.5  9.65         1
1          324          107                  4  4.0   4.5  8.87         1
2          316          104                  3  3.0   3.5  8.00         1
3          322          110                  3  3.5   2.5  8.67         1
4          314          103                  2  2.0   3.0  8.21         0
..         ...          ...                ...  ...   ...   ...       ...
495        332          108                  5  4.5   4.0  9.02         1
496        337          117                  5  5.0   5.0  9.87         1
497        330          120                  5  4.5   5.0  9.56         1
498        312          103                  4  4.0   5.0  8.43         0
499        327          113                  4  4.5   4.5  9.04         0

[500 rows x 7 columns]

In [10]:
scaler = StandardScaler()

In [11]:
arr=scaler.fit_transform(x)

In [12]:
arr

array([[ 1.81923762,  1.77886545,  0.77558214, ...,  1.09894429,
         1.77680627,  0.88640526],
       [ 0.66714832, -0.03160087,  0.77558214, ...,  1.09894429,
         0.48585943,  0.88640526],
       [-0.0418297 , -0.52536441, -0.09979274, ...,  0.01730621,
        -0.95404281,  0.88640526],
       ...,
       [ 1.19888185,  2.10804114,  1.65095702, ...,  1.63976333,
         1.62785086,  0.88640526],
       [-0.39631872, -0.68995225,  0.77558214, ...,  1.63976333,
        -0.24236699, -1.12815215],
       [ 0.93301508,  0.95592621,  0.77558214, ...,  1.09894429,
         0.76721964, -1.12815215]])

In [13]:
df1=pd.DataFrame(arr)

In [14]:
df1.head(10)

0         1         2         3         4         5         6
0  1.819238  1.778865  0.775582  1.137360  1.098944  1.776806  0.886405
1  0.667148 -0.031601  0.775582  0.632315  1.098944  0.485859  0.886405
2 -0.041830 -0.525364 -0.099793 -0.377773  0.017306 -0.954043  0.886405
3  0.489904  0.462163 -0.099793  0.127271 -1.064332  0.154847  0.886405
4 -0.219074 -0.689952 -0.975168 -1.387862 -0.523513 -0.606480 -1.128152
5  1.198882  1.285102  1.650957  1.137360 -0.523513  1.263738  0.886405
6  0.401282  0.297575 -0.099793 -0.377773  0.558125 -0.623031  0.886405
7 -0.750808 -1.019128 -0.975168 -0.377773  0.558125 -1.119549 -1.128152
8 -1.282541 -0.854540 -1.850542 -1.387862 -2.145970 -0.954043 -1.128152
9  0.578526  0.132987 -0.099793  0.127271 -0.523513  0.038993 -1.128152

In [15]:
df1.describe()

0             1             2             3             4  \
count  5.000000e+02  5.000000e+02  5.000000e+02  5.000000e+02  5.000000e+02   
mean   1.762146e-15  1.136868e-15  1.421085e-16 -8.526513e-17  4.263256e-17   
std    1.001002e+00  1.001002e+00  1.001002e+00  1.001002e+00  1.001002e+00   
min   -2.346008e+00 -2.500419e+00 -1.850542e+00 -2.397950e+00 -2.686789e+00   
25%   -7.508077e-01 -6.899523e-01 -9.751676e-01 -8.828175e-01 -5.235128e-01   
50%    4.679255e-02 -3.160087e-02 -9.979274e-02  1.272712e-01  1.730621e-02   
75%    7.557706e-01  7.913384e-01  7.755821e-01  6.323155e-01  5.581253e-01   
max    2.085104e+00  2.108041e+00  1.650957e+00  1.642404e+00  1.639763e+00   

                  5             6  
count  5.000000e+02  5.000000e+02  
mean   3.119283e-15 -7.815970e-17  
std    1.001002e+00  1.001002e+00  
min   -2.940115e+00 -1.128152e+00  
25%   -7.430227e-01 -1.128152e+00  
50%   -2.720919e-02  8.864053e-01  
75%    7.672196e-01  8.864053e-01  
max    2.223672e+00  8.864053e-01

In [16]:
df.shape

(500, 8)

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train, x_test, y_train, y_test = train_test_split(
    arr, y, test_size=0.30, random_state=42)

In [19]:
x_train

array([[ 1.19888185,  1.28510191,  1.65095702, ..., -0.52351283,
         1.26373765,  0.88640526],
       [-1.54840801, -0.8545401 , -0.09979274, ...,  0.01730621,
         0.07209442, -1.12815215],
       [ 0.48990382,  0.46216267,  1.65095702, ...,  0.55812525,
         0.86652324,  0.88640526],
       ...,
       [-1.28254125, -1.34830364, -1.85054249, ..., -1.60515091,
        -2.19533785, -1.12815215],
       [-0.66218548, -0.36077656, -0.97516761, ...,  0.55812525,
        -1.48366203, -1.12815215],
       [-0.21907421, -0.19618871, -0.97516761, ...,  0.01730621,
        -0.5402778 , -1.12815215]])

In [20]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [21]:
lr.fit(x_train,y_train)

LinearRegression()

In [22]:
df.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   
3        322          110                  3  3.5   2.5  8.67         1   
4        314          103                  2  2.0   3.0  8.21         0   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72  
3              0.80  
4              0.65

In [23]:
lr.predict([[337,118,4,4.5,4.5,9.651,0.92]])

array([[12.43077987]])

In [24]:
import pickle
pickle.dump(lr,open('admission_datalr_model.pickle', 'wb'))

In [25]:
%ls # linux command

 Volume in drive C is OS
 Volume Serial Number is E077-265C

 Directory of C:\Users\Jaimin Shah\Data Science


 Directory of C:\Users\Jaimin Shah\Data Science


 Directory of C:\Users\Jaimin Shah\Data Science



File Not Found


In [26]:
pwd()

'C:\\Users\\Jaimin Shah\\Data Science'

In [27]:
model=pickle.load((open('admission_datalr_model.pickle','rb')))

In [28]:
model

LinearRegression()

In [29]:
test1=scaler.transform([[337,118,4,4.5,4.5,9.65,1]])

D:\ANACONDA\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [30]:
model.predict(test1)

array([[0.95967505]])

In [31]:
test2=scaler.transform([[316,104,3,3.0,3.5,8.00,1]])

D:\ANACONDA\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [32]:
df.head()

GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  \
0        337          118                  4  4.5   4.5  9.65         1   
1        324          107                  4  4.0   4.5  8.87         1   
2        316          104                  3  3.0   3.5  8.00         1   
3        322          110                  3  3.5   2.5  8.67         1   
4        314          103                  2  2.0   3.0  8.21         0   

   Chance of Admit   
0              0.92  
1              0.76  
2              0.72  
3              0.80  
4              0.65

In [33]:
model.predict(test2) # also do for remaining 3 data

array([[0.65322038]])

In [34]:
lr.score(x_test,y_test)

0.825630603991949

In [35]:
lr.score(x_train,y_train)

0.8181753126784597

In [36]:
base_preds=lr.predict(x_test)
base_preds

array([[0.91741506],
       [0.79586339],
       [0.57331415],
       [0.71296937],
       [0.81766541],
       [0.86159946],
       [0.47853569],
       [0.65501836],
       [0.82444308],
       [0.80745246],
       [0.72441143],
       [0.73075277],
       [0.65336494],
       [0.93602084],
       [0.82603249],
       [0.51251694],
       [0.83678742],
       [0.59441502],
       [0.53763563],
       [0.56844851],
       [0.66183719],
       [0.55405325],
       [0.71919744],
       [0.79241287],
       [0.78092962],
       [0.60437535],
       [0.95120337],
       [0.84627844],
       [0.62940907],
       [0.74281956],
       [0.55814697],
       [0.73597733],
       [0.54933106],
       [0.86192594],
       [0.65322038],
       [0.73614535],
       [0.55561053],
       [0.9588285 ],
       [0.64202803],
       [0.70997521],
       [0.96801486],
       [0.57117293],
       [0.66729947],
       [0.85771049],
       [0.94159306],
       [0.58142542],
       [0.95967505],
       [0.837

In [37]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [38]:
mean_absolute_error(y_test,base_preds)

0.04267341377223833

In [39]:
y_test.shape

(150, 1)

In [40]:
base_preds.shape

(150, 1)

In [41]:
arr.shape

(500, 7)

In [42]:
y.shape

(500, 1)

In [43]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(350, 7)
(350, 1)
(150, 7)
(150, 1)


In [44]:
np.sqrt(mean_squared_error(y_test,base_preds))

0.060284473965118955

In [45]:
y_test.mean()

Chance of Admit     0.716267
dtype: float64

In [46]:
# Adjusted R squared is calculated by divind the residual mean square error by the total mean square error
# (which is the sample variance of the target field)
# the result is then subtracted from 1
# Adjusted R2 is always less than or equal to R2

In [47]:
# Create adjusted r-squared function, this def formulation is applied to all types for r-squared
def adj_r2(x,y):
    r2=lr.score(x,y)
    n=x.shape[0]
    p=x.shape[1]
    adjusted_r2=1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [48]:
adj_r2(x_test,y_test)

0.8170349295408479

In [49]:
lr.coef_

array([[0.02516588, 0.02082652, 0.00353571, 0.00149993, 0.01407119,
        0.06995721, 0.01029979]])

In [50]:
lr.intercept_

array([0.72350292])

In [51]:
from sklearn.linear_model import Ridge, Lasso, RidgeCV, LassoCV, ElasticNet, ElasticNetCV, LinearRegression

In [52]:
# Liner Regression with LASSO
lassocv = LassoCV(cv=10, max_iter=200000)
lassocv.fit(x_train,y_train)

D:\ANACONDA\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:1563: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LassoCV(cv=10, max_iter=200000)

In [53]:
lassocv.alpha_

0.000599330551621867

In [54]:
lasso = Lasso(alpha=lassocv.alpha_)
lasso.fit(x_train,y_train)

Lasso(alpha=0.000599330551621867)

In [55]:
lasso.score(x_test,y_test)

0.8256392441412117

In [56]:
y_pred = lassocv.predict(x_test)

In [69]:
mean_absolute_error(y_test,y_pred)

0.04289271568273703

In [70]:
np.sqrt(mean_squared_error(y_test,y_pred))

0.06026930826626468

In [57]:
# Create Linear Regression with Ridge
ridgecv = RidgeCV(alphas=np.random.uniform(0,10,50), cv=10)
ridgecv.fit(x_train,y_train)

RidgeCV(alphas=array([5.67669783, 3.71052008, 9.12598312, 7.47488191, 3.46002525,
       4.82119465, 5.5483244 , 9.34728947, 1.46379208, 1.41989056,
       9.00899543, 6.65943844, 4.9105768 , 5.37896642, 0.75961974,
       8.42466561, 3.22251601, 9.47135623, 6.60151275, 3.36804321,
       0.72209528, 8.07568799, 0.6461442 , 4.90729746, 8.56656606,
       9.4792193 , 0.38212508, 4.4964302 , 5.35266981, 2.18983455,
       7.49306622, 5.36107613, 3.14178812, 9.2978835 , 8.57313897,
       8.06449432, 2.15791347, 2.44588565, 1.55711374, 9.06085698,
       1.25167023, 5.73743514, 5.843911  , 0.55498274, 3.31163734,
       5.39167987, 4.13718925, 9.1357721 , 8.54287172, 5.40554701]),
        cv=10)

In [58]:
ridgecv.alpha_

9.47921929847028

In [59]:
ridge_lr=Ridge(alpha=ridgecv.alpha_)
ridge_lr.fit(x_train,y_train)

Ridge(alpha=9.47921929847028)

In [60]:
y_pred = ridge_lr.predict(x_test) 

In [61]:
mean_absolute_error(y_test,y_pred)

0.04289271568273703

In [62]:
np.sqrt(mean_squared_error(y_test,y_pred))

0.06026930826626468

In [63]:
y_test.mean()

Chance of Admit     0.716267
dtype: float64

In [64]:
# Create Linear Regression with ElasticNet
elastic = ElasticNetCV(alphas=None,cv=10)
elastic.fit(x_train,y_train)

D:\ANACONDA\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:1563: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ElasticNetCV(cv=10)

In [65]:
elastic.alpha_

0.0011986611032437343

In [66]:
elastic.l1_ratio_

0.5

In [67]:
elastic_lr=ElasticNet(alpha=elastic.alpha_,l1_ratio=elastic.l1_ratio_)
elastic_lr.fit(x_train,y_train)

ElasticNet(alpha=0.0011986611032437343)

In [68]:
elastic_lr.score(x_test,y_test)

0.8256473988640655